# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum ByteOrderCodec::UInt8 begin
    SBE_LITTLE_ENDIAN = UInt8(0x0)
    SBE_BIG_ENDIAN = UInt8(0x1)
    NULL_VALUE = UInt8(0xff)
end
