# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

export FrameCodec, FrameCodecDecoder, FrameCodecEncoder
abstract type FrameCodec{T} end

struct FrameCodecDecoder{T<:AbstractArray{UInt8}} <: FrameCodec{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    acting_block_length::UInt16
    acting_version::UInt16
    function FrameCodecDecoder(buffer::T, offset::Integer, position_ptr::Ref{Int64},
        acting_block_length::Integer, acting_version::Integer) where {T}
        position_ptr[] = offset + acting_block_length
        new{T}(buffer, offset, position_ptr, acting_block_length, acting_version)
    end
end

struct FrameCodecEncoder{T<:AbstractArray{UInt8},HasSbeHeader} <: FrameCodec{T}
    buffer::T
    offset::Int64
    position_ptr::Base.RefValue{Int64}
    function FrameCodecEncoder(buffer::T, offset::Integer,
        position_ptr::Ref{Int64}, hasSbeHeader::Bool=false) where {T}
        position_ptr[] = offset + 12
        new{T,hasSbeHeader}(buffer, offset, position_ptr)
    end
end

@inline function FrameCodecDecoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    if templateId(header) != UInt16(0x1) || schemaId(header) != UInt16(0x1)
        throw(DomainError("Template id or schema id mismatch"))
    end
    FrameCodecDecoder(buffer, offset + sbe_encoded_length(header), position_ptr,
        blockLength(header), version(header))
end
@inline function FrameCodecEncoder(buffer::AbstractArray, offset::Integer=0;
    position_ptr::Base.RefValue{Int64}=Ref(0),
    header::MessageHeader=MessageHeader(buffer, offset))
    blockLength!(header, UInt16(0xc))
    templateId!(header, UInt16(0x1))
    schemaId!(header, UInt16(0x1))
    version!(header, UInt16(0x0))
    FrameCodecEncoder(buffer, offset + sbe_encoded_length(header), position_ptr, true)
end
sbe_buffer(m::FrameCodec) = m.buffer
sbe_offset(m::FrameCodec) = m.offset
sbe_position_ptr(m::FrameCodec) = m.position_ptr
sbe_position(m::FrameCodec) = m.position_ptr[]
sbe_position!(m::FrameCodec, position) = m.position_ptr[] = position
sbe_block_length(::FrameCodec) = UInt16(0xc)
sbe_block_length(::Type{<:FrameCodec}) = UInt16(0xc)
sbe_template_id(::FrameCodec) = UInt16(0x1)
sbe_template_id(::Type{<:FrameCodec})  = UInt16(0x1)
sbe_schema_id(::FrameCodec) = UInt16(0x1)
sbe_schema_id(::Type{<:FrameCodec})  = UInt16(0x1)
sbe_schema_version(::FrameCodec) = UInt16(0x0)
sbe_schema_version(::Type{<:FrameCodec})  = UInt16(0x0)
sbe_semantic_type(::FrameCodec) = ""
sbe_semantic_version(::FrameCodec) = ""
sbe_acting_block_length(m::FrameCodecDecoder) = m.acting_block_length
sbe_acting_block_length(::FrameCodecEncoder) = UInt16(0xc)
sbe_acting_version(m::FrameCodecDecoder) = m.acting_version
sbe_acting_version(::FrameCodecEncoder) = UInt16(0x0)
sbe_rewind!(m::FrameCodec) = sbe_position!(m, m.offset + sbe_acting_block_length(m))
sbe_encoded_length(m::FrameCodec) = sbe_position(m) - m.offset
@inline function sbe_decoded_length(m::FrameCodec)
    skipper = FrameCodecDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_acting_block_length(m), sbe_acting_version(m))
    sbe_skip!(skipper)
    sbe_encoded_length(skipper)
end

Base.sizeof(m::FrameCodec) = sbe_decoded_length(m)
function Base.convert(::Type{AbstractArray{UInt8}}, m::FrameCodecEncoder{<:AbstractArray{UInt8},true})
    return view(m.buffer, m.offset+1-sbe_encoded_length(MessageHeader):m.offset+sbe_encoded_length(m))
end
function Base.convert(::Type{AbstractArray{UInt8}}, m::FrameCodecEncoder{<:AbstractArray{UInt8},false})
    return view(m.buffer, m.offset+1:m.offset+sbe_encoded_length(m))
end

function irId_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
irId_id(::FrameCodec) = UInt16(0x1)
irId_id(::Type{<:FrameCodec}) = UInt16(0x1)
irId_since_version(::FrameCodec) = UInt16(0x0)
irId_since_version(::Type{<:FrameCodec}) = UInt16(0x0)
irId_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= UInt16(0x0)
irId_encoding_offset(::FrameCodec) = 0
irId_encoding_offset(::Type{<:FrameCodec}) = 0
irId_null_value(::FrameCodec) = Int32(-2147483648)
irId_null_value(::Type{<:FrameCodec}) = Int32(-2147483648)
irId_min_value(::FrameCodec) = Int32(-2147483647)
irId_min_value(::Type{<:FrameCodec}) = Int32(-2147483647)
irId_max_value(::FrameCodec) = Int32(2147483647)
irId_max_value(::Type{<:FrameCodec}) = Int32(2147483647)
irId_encoding_length(::FrameCodec) = 4
irId_encoding_length(::Type{<:FrameCodec}) = 4

@inline function irId(m::FrameCodecDecoder)
    return decode_le(Int32, m.buffer, m.offset + 0)
end
@inline irId!(m::FrameCodecEncoder, value) = encode_le(Int32, m.buffer, m.offset + 0, value)

function irVersion_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
irVersion_id(::FrameCodec) = UInt16(0x2)
irVersion_id(::Type{<:FrameCodec}) = UInt16(0x2)
irVersion_since_version(::FrameCodec) = UInt16(0x0)
irVersion_since_version(::Type{<:FrameCodec}) = UInt16(0x0)
irVersion_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= UInt16(0x0)
irVersion_encoding_offset(::FrameCodec) = 4
irVersion_encoding_offset(::Type{<:FrameCodec}) = 4
irVersion_null_value(::FrameCodec) = Int32(-2147483648)
irVersion_null_value(::Type{<:FrameCodec}) = Int32(-2147483648)
irVersion_min_value(::FrameCodec) = Int32(-2147483647)
irVersion_min_value(::Type{<:FrameCodec}) = Int32(-2147483647)
irVersion_max_value(::FrameCodec) = Int32(2147483647)
irVersion_max_value(::Type{<:FrameCodec}) = Int32(2147483647)
irVersion_encoding_length(::FrameCodec) = 4
irVersion_encoding_length(::Type{<:FrameCodec}) = 4

@inline function irVersion(m::FrameCodecDecoder)
    return decode_le(Int32, m.buffer, m.offset + 4)
end
@inline irVersion!(m::FrameCodecEncoder, value) = encode_le(Int32, m.buffer, m.offset + 4, value)

function schemaVersion_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end
schemaVersion_id(::FrameCodec) = UInt16(0x3)
schemaVersion_id(::Type{<:FrameCodec}) = UInt16(0x3)
schemaVersion_since_version(::FrameCodec) = UInt16(0x0)
schemaVersion_since_version(::Type{<:FrameCodec}) = UInt16(0x0)
schemaVersion_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= UInt16(0x0)
schemaVersion_encoding_offset(::FrameCodec) = 8
schemaVersion_encoding_offset(::Type{<:FrameCodec}) = 8
schemaVersion_null_value(::FrameCodec) = Int32(-2147483648)
schemaVersion_null_value(::Type{<:FrameCodec}) = Int32(-2147483648)
schemaVersion_min_value(::FrameCodec) = Int32(-2147483647)
schemaVersion_min_value(::Type{<:FrameCodec}) = Int32(-2147483647)
schemaVersion_max_value(::FrameCodec) = Int32(2147483647)
schemaVersion_max_value(::Type{<:FrameCodec}) = Int32(2147483647)
schemaVersion_encoding_length(::FrameCodec) = 4
schemaVersion_encoding_length(::Type{<:FrameCodec}) = 4

@inline function schemaVersion(m::FrameCodecDecoder)
    return decode_le(Int32, m.buffer, m.offset + 8)
end
@inline schemaVersion!(m::FrameCodecEncoder, value) = encode_le(Int32, m.buffer, m.offset + 8, value)

function packageName_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

packageName_character_encoding(::FrameCodec) = "UTF-8"
packageName_character_encoding(::Type{<:FrameCodec}) = "UTF-8"
packageName_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= 0
packageName_id(::FrameCodec) = 4
packageName_id(::Type{<:FrameCodec}) = 4
packageName_header_length(::FrameCodec) = 2
packageName_header_length(::Type{<:FrameCodec}) = 2

@inline function packageName_length(m::FrameCodec)
    return decode_le(UInt16, m.buffer, sbe_position(m))
end

@inline function packageName_length!(m::FrameCodecEncoder, n)
    @boundscheck n > 65534 && throw(ArgumentError("length exceeds schema limit"))
    @boundscheck checkbounds(m.buffer, sbe_position(m) + 2 + n)
    return encode_le(UInt16, m.buffer, sbe_position(m), n)
end

@inline function skip_packageName!(m::FrameCodecDecoder)
    len = packageName_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return len
end

@inline function packageName(m::FrameCodecDecoder)
    len = packageName_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline packageName(m::FrameCodecDecoder, ::Type{AbstractArray{T}}) where {T<:Real} = reinterpret(T, packageName(m))
@inline packageName(m::FrameCodecDecoder, ::Type{NTuple{N,T}}) where {N,T<:Real} = (x = reinterpret(T, packageName(m)); ntuple(i -> x[i], Val(N)))
@inline packageName(m::FrameCodecDecoder, ::Type{T}) where {T<:AbstractString} = StringView(rstrip_nul(packageName(m)))
@inline packageName(m::FrameCodecDecoder, ::Type{T}) where {T<:Symbol} = Symbol(packageName(m, StringView))
@inline packageName(m::FrameCodecDecoder, ::Type{T}) where {T<:Real} = reinterpret(T, packageName(m))[]
@inline packageName(m::FrameCodecDecoder, ::Type{T}) where {T<:Nothing} = (skip_packageName!(m); nothing)

@inline function packageName_buffer!(m::FrameCodecEncoder, len)
    packageName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function packageName!(m::FrameCodecEncoder, src::AbstractArray)
    len = sizeof(eltype(src)) * length(src)
    packageName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function packageName!(m::FrameCodecEncoder, src::NTuple)
    len = sizeof(src)
    packageName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{len,UInt8}, src))
end

@inline function packageName!(m::FrameCodecEncoder, src::AbstractString)
    len = sizeof(src)
    packageName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, codeunits(src))
end

@inline packageName!(m::FrameCodecEncoder, src::Symbol) = packageName!(m, to_string(src))
@inline packageName!(m::FrameCodecEncoder, src::StaticString) = packageName!(m, Tuple(src))
@inline packageName!(m::FrameCodecEncoder, src::Real) = packageName!(m, Tuple(src))
@inline packageName!(m::FrameCodecEncoder, ::Nothing) = packageName_buffer!(m, 0)

function namespaceName_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

namespaceName_character_encoding(::FrameCodec) = "UTF-8"
namespaceName_character_encoding(::Type{<:FrameCodec}) = "UTF-8"
namespaceName_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= 0
namespaceName_id(::FrameCodec) = 5
namespaceName_id(::Type{<:FrameCodec}) = 5
namespaceName_header_length(::FrameCodec) = 2
namespaceName_header_length(::Type{<:FrameCodec}) = 2

@inline function namespaceName_length(m::FrameCodec)
    return decode_le(UInt16, m.buffer, sbe_position(m))
end

@inline function namespaceName_length!(m::FrameCodecEncoder, n)
    @boundscheck n > 65534 && throw(ArgumentError("length exceeds schema limit"))
    @boundscheck checkbounds(m.buffer, sbe_position(m) + 2 + n)
    return encode_le(UInt16, m.buffer, sbe_position(m), n)
end

@inline function skip_namespaceName!(m::FrameCodecDecoder)
    len = namespaceName_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return len
end

@inline function namespaceName(m::FrameCodecDecoder)
    len = namespaceName_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline namespaceName(m::FrameCodecDecoder, ::Type{AbstractArray{T}}) where {T<:Real} = reinterpret(T, namespaceName(m))
@inline namespaceName(m::FrameCodecDecoder, ::Type{NTuple{N,T}}) where {N,T<:Real} = (x = reinterpret(T, namespaceName(m)); ntuple(i -> x[i], Val(N)))
@inline namespaceName(m::FrameCodecDecoder, ::Type{T}) where {T<:AbstractString} = StringView(rstrip_nul(namespaceName(m)))
@inline namespaceName(m::FrameCodecDecoder, ::Type{T}) where {T<:Symbol} = Symbol(namespaceName(m, StringView))
@inline namespaceName(m::FrameCodecDecoder, ::Type{T}) where {T<:Real} = reinterpret(T, namespaceName(m))[]
@inline namespaceName(m::FrameCodecDecoder, ::Type{T}) where {T<:Nothing} = (skip_namespaceName!(m); nothing)

@inline function namespaceName_buffer!(m::FrameCodecEncoder, len)
    namespaceName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function namespaceName!(m::FrameCodecEncoder, src::AbstractArray)
    len = sizeof(eltype(src)) * length(src)
    namespaceName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function namespaceName!(m::FrameCodecEncoder, src::NTuple)
    len = sizeof(src)
    namespaceName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{len,UInt8}, src))
end

@inline function namespaceName!(m::FrameCodecEncoder, src::AbstractString)
    len = sizeof(src)
    namespaceName_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, codeunits(src))
end

@inline namespaceName!(m::FrameCodecEncoder, src::Symbol) = namespaceName!(m, to_string(src))
@inline namespaceName!(m::FrameCodecEncoder, src::StaticString) = namespaceName!(m, Tuple(src))
@inline namespaceName!(m::FrameCodecEncoder, src::Real) = namespaceName!(m, Tuple(src))
@inline namespaceName!(m::FrameCodecEncoder, ::Nothing) = namespaceName_buffer!(m, 0)

function semanticVersion_meta_attribute(::FrameCodec, meta_attribute)
    meta_attribute === :presence && return Symbol("required")
    return Symbol("")
end

semanticVersion_character_encoding(::FrameCodec) = "UTF-8"
semanticVersion_character_encoding(::Type{<:FrameCodec}) = "UTF-8"
semanticVersion_in_acting_version(m::FrameCodec) = sbe_acting_version(m) >= 0
semanticVersion_id(::FrameCodec) = 6
semanticVersion_id(::Type{<:FrameCodec}) = 6
semanticVersion_header_length(::FrameCodec) = 2
semanticVersion_header_length(::Type{<:FrameCodec}) = 2

@inline function semanticVersion_length(m::FrameCodec)
    return decode_le(UInt16, m.buffer, sbe_position(m))
end

@inline function semanticVersion_length!(m::FrameCodecEncoder, n)
    @boundscheck n > 65534 && throw(ArgumentError("length exceeds schema limit"))
    @boundscheck checkbounds(m.buffer, sbe_position(m) + 2 + n)
    return encode_le(UInt16, m.buffer, sbe_position(m), n)
end

@inline function skip_semanticVersion!(m::FrameCodecDecoder)
    len = semanticVersion_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return len
end

@inline function semanticVersion(m::FrameCodecDecoder)
    len = semanticVersion_length(m)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline semanticVersion(m::FrameCodecDecoder, ::Type{AbstractArray{T}}) where {T<:Real} = reinterpret(T, semanticVersion(m))
@inline semanticVersion(m::FrameCodecDecoder, ::Type{NTuple{N,T}}) where {N,T<:Real} = (x = reinterpret(T, semanticVersion(m)); ntuple(i -> x[i], Val(N)))
@inline semanticVersion(m::FrameCodecDecoder, ::Type{T}) where {T<:AbstractString} = StringView(rstrip_nul(semanticVersion(m)))
@inline semanticVersion(m::FrameCodecDecoder, ::Type{T}) where {T<:Symbol} = Symbol(semanticVersion(m, StringView))
@inline semanticVersion(m::FrameCodecDecoder, ::Type{T}) where {T<:Real} = reinterpret(T, semanticVersion(m))[]
@inline semanticVersion(m::FrameCodecDecoder, ::Type{T}) where {T<:Nothing} = (skip_semanticVersion!(m); nothing)

@inline function semanticVersion_buffer!(m::FrameCodecEncoder, len)
    semanticVersion_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    return view(m.buffer, pos+1:pos+len)
end

@inline function semanticVersion!(m::FrameCodecEncoder, src::AbstractArray)
    len = sizeof(eltype(src)) * length(src)
    semanticVersion_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(UInt8, src))
end

@inline function semanticVersion!(m::FrameCodecEncoder, src::NTuple)
    len = sizeof(src)
    semanticVersion_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, reinterpret(NTuple{len,UInt8}, src))
end

@inline function semanticVersion!(m::FrameCodecEncoder, src::AbstractString)
    len = sizeof(src)
    semanticVersion_length!(m, len)
    pos = sbe_position(m) + 2
    sbe_position!(m, pos + len)
    dest = view(m.buffer, pos+1:pos+len)
    copyto!(dest, codeunits(src))
end

@inline semanticVersion!(m::FrameCodecEncoder, src::Symbol) = semanticVersion!(m, to_string(src))
@inline semanticVersion!(m::FrameCodecEncoder, src::StaticString) = semanticVersion!(m, Tuple(src))
@inline semanticVersion!(m::FrameCodecEncoder, src::Real) = semanticVersion!(m, Tuple(src))
@inline semanticVersion!(m::FrameCodecEncoder, ::Nothing) = semanticVersion_buffer!(m, 0)

function show(io::IO, m::FrameCodec{T}) where {T}
    println(io, "FrameCodec view over a type $T")
    println(io, "SbeBlockLength: ", sbe_block_length(m))
    println(io, "SbeTemplateId:  ", sbe_template_id(m))
    println(io, "SbeSchemaId:    ", sbe_schema_id(m))
    println(io, "SbeSchemaVersion: ", sbe_schema_version(m))

    writer = FrameCodecDecoder(sbe_buffer(m), sbe_offset(m), Ref(0),
        sbe_block_length(m), sbe_schema_version(m))
    print(io, "irId: ")
    print(io, irId(writer))

    println(io)
    print(io, "irVersion: ")
    print(io, irVersion(writer))

    println(io)
    print(io, "schemaVersion: ")
    print(io, schemaVersion(writer))

    println(io)
    print(io, "packageName: ")
    print(io, packageName(writer, StringView))

    println(io)
    print(io, "namespaceName: ")
    print(io, namespaceName(writer, StringView))

    println(io)
    print(io, "semanticVersion: ")
    print(io, semanticVersion(writer, StringView))

    nothing
end

@inline function sbe_skip!(m::FrameCodecDecoder)
    sbe_rewind!(m)
    skip_packageName!(m)
    skip_namespaceName!(m)
    skip_semanticVersion!(m)
    return
end
