# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum PresenceCodec::UInt8 begin
    SBE_REQUIRED = UInt8(0x0)
    SBE_OPTIONAL = UInt8(0x1)
    SBE_CONSTANT = UInt8(0x2)
    NULL_VALUE = UInt8(0xff)
end
