# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum PrimitiveTypeCodec::UInt8 begin
    NONE = UInt8(0x0)
    CHAR = UInt8(0x1)
    INT8 = UInt8(0x2)
    INT16 = UInt8(0x3)
    INT32 = UInt8(0x4)
    INT64 = UInt8(0x5)
    UINT8 = UInt8(0x6)
    UINT16 = UInt8(0x7)
    UINT32 = UInt8(0x8)
    UINT64 = UInt8(0x9)
    FLOAT = UInt8(0xa)
    DOUBLE = UInt8(0xb)
    NULL_VALUE = UInt8(0xff)
end
