# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum SignalCodec::UInt8 begin
    BEGIN_MESSAGE = UInt8(0x1)
    END_MESSAGE = UInt8(0x2)
    BEGIN_COMPOSITE = UInt8(0x3)
    END_COMPOSITE = UInt8(0x4)
    BEGIN_FIELD = UInt8(0x5)
    END_FIELD = UInt8(0x6)
    BEGIN_GROUP = UInt8(0x7)
    END_GROUP = UInt8(0x8)
    BEGIN_ENUM = UInt8(0x9)
    VALID_VALUE = UInt8(0xa)
    END_ENUM = UInt8(0xb)
    BEGIN_SET = UInt8(0xc)
    CHOICE = UInt8(0xd)
    END_SET = UInt8(0xe)
    BEGIN_VAR_DATA = UInt8(0xf)
    END_VAR_DATA = UInt8(0x10)
    ENCODING = UInt8(0x11)
    NULL_VALUE = UInt8(0xff)
end
