# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

module Uk_co_real_logic_sbe_ir_generated

using EnumX
using StaticStrings
using StringViews
using UnsafeArrays

include("Utils.jl")
include("ByteOrderCodec.jl")
include("SignalCodec.jl")
include("PresenceCodec.jl")
include("PrimitiveTypeCodec.jl")
include("MessageHeader.jl")
include("VarDataEncoding.jl")
include("FrameCodec.jl")
include("TokenCodec.jl")

export sbe_buffer,
    sbe_offset,
    sbe_position_ptr,
    sbe_position,
    sbe_position!,
    sbe_block_length,
    sbe_template_id,
    sbe_schema_id,
    sbe_schema_version,
    sbe_semantic_type,
    sbe_semantic_version,
    sbe_acting_block_length,
    sbe_acting_version,
    sbe_rewind!,
    sbe_encoded_length,
    sbe_decoded_length,
    sbe_skip!,
    decode,
    encode

function decode end
function encode end
end
