<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.rubustechnologies.sbejl</groupId>
  <artifactId>sbetool-test-dependencies</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>

  <properties>
    <sbe.version>1.40.1</sbe.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>uk.co.real-logic</groupId>
      <artifactId>sbe-all</artifactId>
      <version>${sbe.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
