# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

module Baseline

using EnumX
using MappedArrays
using StaticArrays
using StaticStrings
using StringViews
using UnsafeArrays

include("Utils.jl")
include("BooleanType.jl")
include("Model.jl")
include("BoostType.jl")
include("OptionalExtras.jl")
include("MessageHeader.jl")
include("Booster.jl")
include("GroupSizeEncoding.jl")
include("VarStringEncoding.jl")
include("VarAsciiEncoding.jl")
include("Engine.jl")
include("Car.jl")

export sbe_buffer,
    sbe_offset,
    sbe_position_ptr,
    sbe_position,
    sbe_position!,
    sbe_block_length,
    sbe_template_id,
    sbe_schema_id,
    sbe_schema_version,
    sbe_semantic_type,
    sbe_semantic_version,
    sbe_acting_block_length,
    sbe_acting_version,
    sbe_rewind!,
    sbe_encoded_length,
    sbe_decoded_length,
    sbe_skip!,
    decode,
    encode

function decode end
function encode end
end
