# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum BooleanType::UInt8 begin
    F = UInt8(0x0)
    T = UInt8(0x1)
    NULL_VALUE = UInt8(0xff)
end
