# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum BoostType::UInt8 begin
    TURBO = UInt8(0x54)
    SUPERCHARGER = UInt8(0x53)
    NITROUS = UInt8(0x4e)
    KERS = UInt8(0x4b)
    NULL_VALUE = UInt8(0x0)
end
