# Generated SBE (Simple Binary Encoding) message codec
# Code generated by SBE. DO NOT EDIT.

@enumx T=SbeEnum Model::UInt8 begin
    A = UInt8(0x41)
    B = UInt8(0x42)
    C = UInt8(0x43)
    NULL_VALUE = UInt8(0x0)
end
